### ISSUE TITLE
AltStore PAL & SideStore repo

### ISSUE THREAD

**Issue by Max2github** [Auties00/Artemis#1]
AltStore PAL and SideStore expect the repo to have an identifier. See https://docs.sidestore.io/docs/advanced/app-sources/

Unfortunately I did not find it in the AltStore Docs, but when looking into the source code, it can be seen.

**Comment by Auties00** [comment]
Added, i'll try to release it on the AltStore PAL soon
I'm waiting for them to email me back my token
